# Generated by Django 2.0.7 on 2018-07-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=50)),
                ('back', models.CharField(max_length=100)),
                ('subTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexcards.SubTopic')),
            ],
        ),
    ]
